{{- if .Values.services.airflowWrapperService.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name:  {{ include "dss-service.api.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app:  {{ include "dss-service.api.name" . }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.airflowWrapper.ports.containerPort }}
      name: {{ .Values.airflowWrapper.ports.name }}
  selector:
   app: {{ include "dss-service.api.name" . }}
{{- end -}}