{{- if .Values.services.dssServiceIngress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.dssServiceApplication.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "false"
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Values.dssServiceApplication.ingress.path }}
        backend:
          serviceName: {{ .Values.dssServiceApplication.name }}
          servicePort: {{ .Values.dssServiceApplication.ports.port }}
{{- end -}}