{{- if .Values.services.dssClientService.enabled -}}
apiVersion: v1
data:
  api.config.json: |
    {
      "apiUrl": "http://10.113.104.24:31353/dss-app-service",
      "keycloakConfig": {
          "url": "http://10.113.104.24:31353/auth",
          "realm": "sys-testing",
          "clientId": "data-science-studio-app-v2"
      },
      "commonServicesApiUrl": "http://10.113.104.24:32311"
    }
kind: ConfigMap
metadata:
  name: data-science-studio-api-config-v2
{{- end -}}
