{{- if .Values.services.dssClientService.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dss-service.client.name" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "dss-service.client.name" . }}
spec:
  replicas: {{ .Values.dssClintApplication.replicas }}
  selector:
    matchLabels:
      app: {{ include "dss-service.client.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "dss-service.client.name" . }}
    spec:
      containers:
        - name: {{ .Values.dssClintApplication.name }}
          image: {{ .Values.dssClintApplication.image }}
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: {{ .Values.dssClintApplication.ports.port }}
          volumeMounts:
            - name: {{ .Values.dssClintApplication.volumeMounts.name }}
              mountPath: {{ .Values.dssClintApplication.volumeMounts.mountPath }}
              subPath: {{ .Values.dssClintApplication.volumeMounts.subPath }}
      volumes:
        - name: {{ .Values.dssClintApplication.volumeMounts.name }}
          configMap:
            name: {{ .Values.dssClintApplication.volumes.configMapName }}

{{- end -}}