{{- if .Values.services.dssClientIngress.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.dssClintApplication.ingress.name }}
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/strip-path: "false"
spec:
  rules:
  - http:
      paths:
      - path: /{{ .Values.dssClintApplication.ingress.name }}
        backend:
          serviceName: {{ .Values.dssClintApplication.name }}
          servicePort: {{ .Values.dssClintApplication.ports.name }}
{{- end -}}
