tenant: dss-ingress
airflow:
  name: airflow-webserver
  replicas: 1
  image: 10.113.56.67/ngp-develop/dss-airflow-operators:20210422172713
  loadex: "n"
  executor: Local
  username: airflow
  password: airflow
  baseUrlPath: http://10.113.104.24:31353/airflow-operator
  security:
    username: airflow
    firstname: ngp
    lastname: admin
    email: nitin.j@subex.com
    password: airflow

  db: airflow
  host: postgres-v1
  type: ClusterIP
  ports:
    postgresPort: 5432
    airflowPort: 8080
    nodePort: 30223
    name: http
  volumes:
    basePath: /home/subex/charts/stable/airflow-deployment/dss-airflow-operators
  
  ingress:
    name: airflow-operator
    path: airflow-operator
  
postgres:
  name: postgres-v1
  image: postgres:9.6.14
  replicas: 1
  username: airflow
  password: airflow
  db: airflow
  ports:
    containerPort: 5432
    name: http
#################### enable or disable services ######################
services:
  ingress:
      enabled: true
  airflow:
      enabled: true
  postgres:
      enabled: true
