############################ DSS middle layer (service) #####################################
dssServiceApplication:
  name: data-science-studio-app-service
  image:
    repository: REGISTRY_PROJECT/data-science-studio-service
    tag: "BUILD_NUMBER"
  replicas: 1
  ports:
    port: 8080
    name: http
  volumeMounts:
    configName: config-volume
    configMountPath:  /deployments/config
    sharedName: shared-volume
    sharedMountPath: /root/.ngp
    uploadName: upload-volume
    uploadMountPath: /upload
  environment:
    servicePrecondition: "ngp-postgres:5432"
  volumes:
    configMapName: data-science-studio-application-properties-v1
    sharedClaimName: shared-pv-claim
    uploadClaimName: uploads-pv-claim

  ingress:
    name: data-science-studio-app-service-ingress
    path: dss-app-service

############################ Enable/Disable application services ##############################
services:
  dssServiceService:
      enabled: true
  dssServiceIngress:
      enabled: true