############################ DSS middle layer (service) #####################################
dssServiceApplication:
  name: data-science-studio-app-service
  image: 10.113.56.67/ngp-develop/data-science-studio-service:20210423152144
  replicas: 1
  ports:
    port: 8080
    name: http
  volumeMounts:
    configName: config-volume
    configMountPath:  /deployments/config
    sharedName: shared-volume
    sharedMountPath: /root/.ngp
    uploadName: upload-volume
    uploadMountPath: /upload
  environment:
    servicePrecondition: "ngp-postgres:5432"
  volumes:
    configMapName: data-science-studio-application-properties-v1
    sharedClaimName: shared-pv-claim
    uploadClaimName: uploads-pv-claim

  ingress:
    name: data-science-studio-mid-service
    path: data-science-studio-mid-service

############################ Enable/Disable application services ##############################
services:
  dssServiceService:
      enabled: true
  dssServiceIngress:
      enabled: true