########################### Airflow wrapper ########################################
tenant: dss-ingress
airflowWrapper:
  name: dss-airflow-service-service
  image: 10.113.56.67/ngp-develop/dss-airflow-service-service:20210422195110
  type: ClusterIP
  ports:
    containerPort: 8080
    name: http
    nodePort: 30334
  volumeMounts:
    dssConfig: 
      claimName: dss-airflow-service-application-properties-v1
      path: /deployments/config
    dssShared:
      claimName: shared-pv-claim
      path: /root/.ngp
    dssLogs:
      claimName: logs-pvc
      path: /usr/local/airflow/logs
    dssDags:
      claimName: dags-pvc
      path: /usr/local/airflow/dags
    dssData:
      claimName: data-pvc
      path: /usr/local/airflow/data
    dssOutput:
      claimName: output-pvc
      path: /usr/local/airflow/output
    dssModelrepository:
      claimName: modelrepository-pvc
      path: /usr/local/airflow/modelrepository

  environment:
    servicePrecondition: "ngp-postgres:5432"

  ingress:
    name: data-science-studio-airflow-service
    path: data-science-studio-airflow-service

############################ Enable/Disable application services ##############################
services:
  airflowWrapperIngress:
      enabled: true
  airflowWrapperService:
      enabled: true 